spring:
  application:
    name: server
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/newsdb
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true